# Run:
# sudo docker compose -f compose.prod.yml up

services:
  api:
    image: node:18-alpine
    working_dir: /app
    command: npx nx serve api --configuration=production
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - NX_DAEMON=false # Disable the Nx Daemon for production.

  client:
    image: node:18-alpine
    working_dir: /app
    command: npx nx start client
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4000
      - NX_DAEMON=false
    depends_on:
      - api

volumes:
  node-modules:
