services:
  init:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "
      npm install --legacy-peer-deps &&
      npm cache clean --force
      "
    volumes:
      - ./:/app
