# As we run apps independently in different containers "implicitDependencies"
# and "dependsOn" are disabled in "project.json"

services:
  dev-db:
    image: postgres:13
    environment:
      PGPORT: ${DEV_POSTGRES_PORT}
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    ports:
      - '${DEV_POSTGRES_PORT}:${DEV_POSTGRES_PORT}'
    volumes:
      - v-dev-postgres:/var/lib/postgresql/data
    networks:
      - net-dev

  dev-api:
    image: node:18-alpine
    command: >
      sh -c "
        cp -r /app/.vscode/tmp_docker/node_modules/@nx /app/node_modules/ &&
        npx nx serve api --configuration=development --verbose
      "
    environment:
      - NODE_ENV=development
      # App
      - HOST=${DEV_API_HOST}
      - PORT=${DEV_API_PORT}
      # DB
      - DB_HOST=dev-db
      - DB_PORT=${DEV_POSTGRES_PORT}
      - DB_USER=${DEV_POSTGRES_USER}
      - DB_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - DB_DB=${DEV_POSTGRES_DB}
      # Enable the Nx Daemon for development
      - NX_DAEMON=true
    ports:
      - '${DEV_API_PORT}:${DEV_API_PORT}'
    working_dir: /app
    volumes:
      - ./:/app # Mirror the app code
      - v-dev-api-nx:/app/.nx
      - v-dev-api-tmp:/app/tmp
      - v-dev-api-dist:/app/dist
      # node_modules/@nx
      - ./node_modules/@nx/:/app/.vscode/tmp_docker/node_modules/@nx/
      - type: tmpfs
        target: /app/node_modules/@nx
    depends_on:
      - dev-db
    networks:
      - net-dev

  dev-client:
    image: node:18-alpine
    command: >
      sh -c "
        cp -r /app/.vscode/tmp_docker/node_modules/@nx /app/node_modules/ &&
        npx nx dev client
      "
    environment:
      - NODE_ENV=development
      # App
      - HOST=${DEV_CLIENT_HOST}
      - PORT=${DEV_CLIENT_PORT}
      # Enable the Nx Daemon for development
      - NX_DAEMON=true
    ports:
      - '${DEV_CLIENT_PORT}:${DEV_CLIENT_PORT}'
    working_dir: /app
    volumes:
      - ./:/app # Mirror the app code
      - v-dev-client-nx:/app/.nx
      - v-dev-client-tmp:/app/tmp
      - v-dev-client-dist:/app/dist
      # node_modules/@nx
      - ./node_modules/@nx/:/app/.vscode/tmp_docker/node_modules/@nx/
      - type: tmpfs
        target: /app/node_modules/@nx
    depends_on:
      - dev-db
      - dev-api
    networks:
      - net-dev

volumes:
  v-dev-postgres:
  v-dev-api-nx:
  v-dev-api-tmp:
  v-dev-api-dist:
  v-dev-client-nx:
  v-dev-client-tmp:
  v-dev-client-dist:

networks:
  net-dev:
