version: '3'

services:
  api:
    image: node:18-alpine
    working_dir: /app
    command: npx nx run api:serve
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - events-platform-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000

volumes:
  events-platform-node-modules:
