# First time setup.
# We need to run the following command to install the node_modules
# in the "events-platform-node-modules" volume.
# docker compose -f docker-compose.init.yml up

version: '3'

services:
  api:
    image: node:18-alpine
    working_dir: /app
    command: npm install
    volumes:
      - .:/app
      - events-platform-node-modules:/app/node_modules

volumes:
  events-platform-node-modules:
